### ISSUE TITLE
0.11.7 rpm package doesn't let me open notes.

### ISSUE THREAD

**Issue by cdayjr** [SkYNewZ/Boostnote-packages#2]
This was my first stop when I tried to get Boostnote working on my Fedora 28 install. Unfortunately there was an issue where I couldn't open notes for some reason. After running into the same issue compiling Boostnote from source myself, I believe the cause is [this issue](https://github.com/BoostIO/Boostnote/issues/2204). I posted a comment with a fix for it.

**Comment by dbjsy** [comment]
Hello

That issue still exists for 0.11.8. I had to switch back to 0.11.4.

**Comment by rborer** [comment]
I'm also experiencing this issue, is it related to the rpm package itself?

**Comment by rborer** [comment]
Responding to myself: the issue https://github.com/BoostIO/Boostnote/issues/2204 although closed is not part of a boostnote release yet, so wait & yee :-)

**Comment by cdayjr** [comment]
I'm not sure if it was rpm-package specific. I think it was as I was able to get Boostnote working using `alien` converting the official `.deb` to a `.rpm` though I'm not sure why that would be the case.
