### ISSUE TITLE
Fedora 29 - segmentation fault

### ISSUE THREAD

**Issue by dbjsy** [SkYNewZ/Boostnote-packages#3]
Hi,
I have recently updated to Fedora 29 and Boostnote crashes with segmentation fault:
![image](https://user-images.githubusercontent.com/8529293/48191295-a0cafa80-e33c-11e8-86ae-26fa4d3406c1.png)

It happens for versions:

![image](https://user-images.githubusercontent.com/8529293/48192268-36678980-e33f-11e8-9479-2fd2e7231e34.png)

Best regards,
Damian

**Comment by SkYNewZ** [comment]
Hi!

I think this was related to your `glibc` lib.
Can you check this : https://github.com/electron/electron/issues/13972 https://github.com/Microsoft/vscode/issues/55934

**Comment by SkYNewZ** [comment]
Great! Thank for using my builing CI :+1:
