### ISSUE TITLE
Version 0.11.12 is out

### ISSUE THREAD

**Issue by rborer** [SkYNewZ/Boostnote-packages#6]
Hi,

Thanks for this very useful packaging work :+1: 

I just saw that Boostnote 0.11.12 is out (https://github.com/BoostIO/Boostnote/releases/tag/v0.11.12). Any chance to have it packaged soon?

Thanks again!

**Comment by SkYNewZ** [comment]
You can have the (v0.11.15)[https://github.com/SkYNewZ/Boostnote-packages/releases/tag/v0.11.15] 😃 
Sorry for late, I don't check their releases all days ^^

**Comment by rborer** [comment]
Thanks a lot @SkYNewZ !
